/**
 * M1's acceptance test: composite the hand-authored Black Crypt
 * `slots.json` (fixtures/ copy of `crawl/public/assets/blackcrypt/amiga/dungeon/slots.json`,
 * plus its `dungeon-bcdfx` atlas) into a 320x200 `IndexedSurface`, and
 * assert the result byte-for-byte against a golden fixture.
 *
 * The golden bytes were generated by this exact pipeline (PieceBank decode
 * -> compositeSlotTable), then visually verified by rendering them to a
 * PNG and eyeballing it: a receding corridor with symmetric left/right
 * mortared-stone side walls converging toward a distant capped end,
 * cobbled floor, stone ceiling — matching
 * `docs/blackcrypt/amiga/data-structure.md`'s description of what this
 * scene should look like, with zero background (index 0) pixels inside
 * the 208x140 viewport (no gaps) and zero non-background pixels outside
 * it (no bleed). Only after that visual check did the byte array get
 * checked in as `fixtures/corridor-golden.b64`. If a future change makes
 * this test fail, the fix is almost always in the ~200 lines of
 * blit/mirror/clip math (`IndexedSurface.blit`, `PieceBank.fromRGBA`,
 * `compositeSlotTable`'s draw order) — re-render and look at it; don't
 * update the golden fixture to match a render that looks wrong.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { PNG } from 'pngjs';
import { PieceBank } from '../raster/PieceBank.ts';
import { IndexedSurface } from '../raster/IndexedSurface.ts';
import { compositeSlotTable } from '../raster/composite.ts';
import { validateSlotTableFile } from '../schema/validate.ts';
import type { AtlasMeta } from '@seer/core';

const FIXTURES = fileURLToPath(new URL('./fixtures/', import.meta.url));

function loadSurface() {
  const pngBuf = readFileSync(`${FIXTURES}dungeon-bcdfx.png`);
  const png = PNG.sync.read(pngBuf);
  const atlas = JSON.parse(readFileSync(`${FIXTURES}dungeon-bcdfx.json`, 'utf8')) as AtlasMeta;
  const slots = validateSlotTableFile(JSON.parse(readFileSync(`${FIXTURES}slots.json`, 'utf8')));

  const bank = PieceBank.fromRGBA(new Uint8Array(png.data), png.width, png.height, atlas);
  const surface = new IndexedSurface(slots.surface.width, slots.surface.height);

  const bankRef = slots.banks[0];
  if (!bankRef) throw new Error('fixtures/slots.json has no banks');
  compositeSlotTable(surface, { [bankRef.id]: bank }, slots);

  return { surface, bank, slots };
}

describe('corridor golden render (M1)', () => {
  it('composites the hand-authored Black Crypt slots.json to the byte-exact golden framebuffer', () => {
    const { surface } = loadSurface();
    const golden = new Uint8Array(Buffer.from(readFileSync(`${FIXTURES}corridor-golden.b64`, 'utf8'), 'base64'));
    expect(surface.data.length).toBe(golden.length);
    expect(Array.from(surface.data)).toEqual(Array.from(golden));
  });

  it('fully covers the 208x140 viewport with real art (no gaps)', () => {
    const { surface, slots } = loadSurface();
    const { width, height } = slots.viewport;
    let backgroundPixelsInViewport = 0;
    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        if (surface.data[y * surface.width + x] === 0) backgroundPixelsInViewport++;
      }
    }
    expect(backgroundPixelsInViewport).toBe(0);
  });

  it('draws nothing outside the 208x140 viewport (no bleed)', () => {
    const { surface, slots } = loadSurface();
    const { width, height } = slots.viewport;
    let nonBackgroundOutsideViewport = 0;
    for (let y = 0; y < surface.height; y++) {
      for (let x = 0; x < surface.width; x++) {
        if (x < width && y < height) continue;
        if (surface.data[y * surface.width + x] !== 0) nonBackgroundOutsideViewport++;
      }
    }
    expect(nonBackgroundOutsideViewport).toBe(0);
  });
});
